### ISSUE TITLE
List views error out

### ISSUE THREAD

**Issue by 2spotsplus1** [tomansley/SimpliListViews#10]
**Describe the bug**
I recently installed SimpliList, I ran the initialization but all the views produced this error.

Exception during ListViewProcessBatch.execute() - Illegal character(s) in message header value: Bearer lse},{"index":215,"name":"HideOtherInfluenceGetStarted","value":false},{"index":216,"name":"HideFeedToggleGuidedTour","value":false},{"index":268,"name":"ShowChatterTab178GuidedTour","value":false},{"index":275,"name":"HidePeopleTabDeprecationMsg","value":false},{"index":276,"name":"HideGroupTabDeprecationMsg","value":false},{"index":224,"name":"HideUnifiedSearchGuidedTour","value":true},{"index":226,"name":"ShowDevContextMenu","value":false},{"index":227,"name":"HideWhatRecommenderForActivityQueues","value":false},{"index":228,"name":"HideLiveAgentFirstTimeSetupMsg","value":false},{"index":232,"name":"HideGroupAllowsGuestsMsgOnMemberWidget","value":false},{"index":233,"name":"HideGroupAllowsGuestsMsg","value":false},{"index":234,"name":"HideWhatAreGuestsMsg","value":false},{"index":235,"name":"HideNowAllowGuestsMsg","value":false},{"index":236,"name":"HideSocialAccountsAndContactsGuidedTour","value":true},{"index":237,"name":"HideAnalyticsHomeGuidedTour","value":true},{"index":238,"name":"ShowQuickCreateGuidedTour","value":false},{"index":245,"name":"HideFilePageGuidedTour","value":false},{"index":250,"name":"HideForecastingGuidedTour","value":false},{"index":251,"name":"HideBucketFieldGuide","value":false},{"index":263,"name":"HideSmartSearchCallOut","value":true},{"index":273,"name":"ShowForecastingQuotaAttainment","value":false},{"index":280,"name":"HideForecastingQuotaColumn","value":false},{"index":301,"name":"HideManyWhoGuidedTour","value":false},{"index":298,"name":"HideFileSyncBannerMsg","value":false},{"index":299,"name":"HideTestConsoleGuidedTour","value":false},{"index":302,"name":"HideManyWhoInlineEditTip","value":false},{"index":303,"name":"HideSetupV2WelcomeMessage","value":false},{"index":312,"name":"ForecastingShowQuantity","value":false},{"index":313,"name":"HideDataImporterIntroMsg","value":false},{"index":314,"name":"HideEnvironmentHubLightbox","value":false},{"index":316,"name":"HideSetupV2GuidedTour","value":true},{"index":317,"name":"HideFileSyncMobileDownloadDialog","value":false},{"index":322,"name":"HideEnhancedProfileHelpBubble","value":false},{"index":328,"name":"ForecastingHideZeroRows","value":false},{"index":330,"name":"HideEmbeddedComponentsFeatureCallout","value":true},{"index":341,"name":"HideDedupeMatchResultCallout","value":false},{"index":340,"name":"HideS1BrowserUI","value":false},{"index":346,"name":"HideS1Banner","value":false},{"index":358,"name":"HideEmailVerificationAlert","value":false},{"index":354,"name":"HideLearningPathModal","value":false},{"index":359,"name":"HideAtMentionsHelpBubble","value":false},{"index":368,"name":"LightningExperiencePreferred","value":false},{"index":373,"name":"PreviewLightning","value":false}],"networkId":"","uiTheme":"Theme3","uiSkin":"Theme3","userName":"katherine.olsen@adp.com","userId":"0054P000009bZLU","isCurrentlySysAdminSU":false,"renderMode":"RETRO","startOfWeek":"1","vfDomainPattern":"adptrialorg--(?:[^.]+).visualforce.com","auraDomain":"adptrialorg.lightning.force.com","orgPreferences":[{"index":257,"name":"TabOrganizer","value":true},{"index":113,"name":"GroupTasks","value":true}],"siteUrlPrefix":"","isDefaultNetwork":true,"timeFormat":"h:mm a"}); </script><script type="text/javascript"> var MOTIF_KEY='Home';</script><link rel="shortcut icon" href="https://adptrialorg.my.salesforce.com/favicon.ico" /> <link rel="manifest" href="/one/manifest.json?f345a08ce6028f2543ce95a8bb38961a" /> <script src="/jslibrary/1590082528228/sfdc/Security.js"></script><script>ClientHash.prototype.needsClientHash('sid_Client','P000009bZLUP000000jbm7','::','/servlet/servlet.ClientHashValidator?ResponseRequestedURL=%2Fapex%2Fsimpli_lv__sessionid%3Finline%3D1');</script></head><body onUnload="if(this.bodyOnUnload)bodyOnUnload();" onBeforeUnload="if(this.bodyOnBeforeUnload){var s=bodyOnBeforeUnload();if(s)return s;}" onLoad="if(this.bodyOnLoad)bodyOnLoad();" class="hasMotif homeTab  apexPageInline sfdcBody brandQuaternaryBgr" onFocus="if(this.bodyOnFocus)bodyOnFocus();">  <span id="j_id0"></span>     Start00D4P000000jbm7!AQkAQL1igddsFOWeGrEtHkWvv0BlvfcU9PQC9.1NuRVLNAK6jSWCLyx5ixb1GT6fEdX9cb5Y_1sSa2zoVpgEIOzIS1XzYrAn - line: 55 - (simpli_lv)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by tomansley** [comment]
What version of Salesforce are you using? i.e. Enterprise, Unlimited, Professional

**Comment by 2spotsplus1** [comment]
Unlimited.
Thanks
Kathy

**Comment by 2spotsplus1** [comment]
Weird…I reran the list view refresh and they are appearing now…
Thanks!
Kathy

**Comment by tomansley** [comment]
Not sure what happened here. If this occurs again please reopen the issue.
