### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by sfcase** [tomansley/SimpliListViews#107]
**Describe the bug**
When I download it as CSV, the Korean breakage. and date come out as an attached file.
1900223444 -> YYYY-MM-DD 
I need to change to UTF-8 format in Excel to prevent text breakage. However, the date is still expressed as a long number.

**Simpli List View Version**
2.123

**Desktop (please complete the following information):**
 - chrome

![error](https://user-images.githubusercontent.com/103248307/162400901-6707592d-7262-463a-85c8-42f7bc40059b.png)

**Comment by tomansley** [comment]
Thank you for submitting this issue. I have found what the problem is and resolved the bug. It will be available in the next released version.
