### ISSUE TITLE
Conditional Highlighting not working for Date field

### ISSUE THREAD

**Issue by sjtorre16** [tomansley/SimpliListViews#11]
**Describe the bug**
Conditional Highlighting does not highlight based on greater or less than field filter on a date field.

**To Reproduce**
1. Any list view with a regular Date field (not Date\Time)
2. Click on 'Settings' Cog Wheel
3. Click on 'Highlighting' Tab
4. Attempt to filter on selected 'Date' field with a less than or greater than value based on date EX: Birthdate < 2021-01-01
5. Click + button to add and 'Save'.
6. 'Simpli List View' does not highlight upon save and if you attempt to refresh the 'Simpli List View' breaks with error "There was an error retrieving the data, please see an administrator undefined". and there is no way to again edit the particular view

**Expected behavior**
After adding the conditional highlighting and saving, the list view should highlight the intended data and allow future edits of the 'Simpli List View'.

**Screenshots**
![SS1](https://user-images.githubusercontent.com/79225014/110366266-0c5c2a00-8014-11eb-8a32-36e4a7d96046.PNG)
![SLVerror](https://user-images.githubusercontent.com/79225014/110366281-0fefb100-8014-11eb-927f-0a9946cf0647.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [89.0.4389.82]

**Comment by sjtorre16** [comment]
FYI, I also attempted to filter date in the below format example to no avail:

EX: Date field 'Birthdate' < 1/1/2021

I realized that on regular list views in Salesforce, the 'Date' format needs to be in this above format and NOT 2021-01-01 however the conditional formatting still did not work.  The field that I'm working with is a true 'Date' field and not a 'Date\Time' or 'Text' data type returned field so I'm quite sure this is a bug.

Thanks for fixing the previously reported Date\Time bug so quickly.  I would appreciate if you could look into this one as my company is in need of your App's solution.

Thanks,

Sam

**Comment by tomansley** [comment]
Hi Sam,

Thanks for submitting the issue and for providing such useful screenshots
and information.

I'll take a look and see what I find.

Cheers
Tom

**Comment by sjtorre16** [comment]
No problem and thank you so much Tom!

Cheers,
Sam

**Comment by tomansley** [comment]
This issue has been resolved for both Date and DateTime types and will be available in the next release which should be available in the next day. Please note the format of the date/datetime. If it is not the same format as the list view the highlighting results could be unpredictable.

![Screen Shot 2021-03-08 at 9 52 35 PM](https://user-images.githubusercontent.com/375321/110416262-00468b80-8059-11eb-849e-420eae5332f3.png)

![Screen Shot 2021-03-08 at 9 53 01 PM](https://user-images.githubusercontent.com/375321/110416290-118f9800-8059-11eb-9fc3-9644e83da307.png)

I will close the issue once the next release is available.

**Comment by sjtorre16** [comment]
Great Tom, thank you so much!  I look forward to downloading the next release in our SF sandbox!

Cheers,
Sam

**Comment by tomansley** [comment]
A new release (1.68) has been posted to the appexchange - https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3A00000FZ7BDUA1

I will go ahead and close this bug. Please reopen if issues are still seen.

Cheers
Tom
