### ISSUE TITLE
Custom List views not retrieving data

### ISSUE THREAD

**Issue by Levijos95** [tomansley/SimpliListViews#114]
**Describe the bug**
When we create a custom list views, no records are being retrieved. Seems like the query is not formed correctly per the list views logs. Plus, the custom list view documentation is outdated.

**Simpli List View Version**
VersionSpring 2022 / 2.135.0

**To Reproduce**
1. Create a new custom list view
2. Add it to a new page or search for it in the everything example
3. Data will be empty
4. Check the list view logs

**Expected behavior**
I expect to render the custom list view according to the info added

**Screenshots**
![image](https://user-images.githubusercontent.com/84727821/181038045-508ab722-174d-4778-bbfd-d73b00650c2c.png)
<img width="875" alt="image" src="https://user-images.githubusercontent.com/84727821/181038381-e4bea28a-00fe-4fe9-8b0f-b08b9d42d151.png">

**Desktop (please complete the following information):**
 - Chrome

**Comment by Levijos95** [comment]
Hello,

Sure thing

Select CaseNumber from case

Thanks

**Comment by tomansley** [comment]
I believe the SOQL statement is case sensitive.

 

Could you try the following – 

 

SELECT CaseNumber FROM Case

**Comment by Levijos95** [comment]
Thanks !

Seems like it worked

Regards
