### ISSUE TITLE
No core list view created

### ISSUE THREAD

**Issue by prelily** [tomansley/SimpliListViews#117]
**Describe the bug**
Hi Tom,
There is no core list view available in my org after fresh. Only the 5 default custom list view available.
Could you please advise if there's anything I can do? Thank you

**Simpli List View Version**
2.135

**To Reproduce**
'SLV Admin"App and "List Views"Tab
NO core list view available.

**Expected behavior**
Salesforce list views should be created as core list views in SLV 

**Screenshots**
![image](https://user-images.githubusercontent.com/111689684/185792193-bf3dd2ac-baea-4bf9-9cc1-2d18996d35e1.png)

**Desktop (please complete the following information):**
Chrome
**Additional context**

**Comment by prelily** [comment]
Hi Tom,

Don't worry about it. I have figured it out to be access issue.

Thank you for providing the function

**Comment by tomansley** [comment]
Great to hear you were able to resolve the issue. If you let me know how you resolved it I can add the resolution into the FAQ documentation.

Enjoy SLV!!
________________________________

**Comment by tomansley** [comment]
User resolved.
