### ISSUE TITLE
When exporting Simpli List views, file exports as a .txt and not .csv file type

### ISSUE THREAD

**Issue by sjtorre16** [tomansley/SimpliListViews#13]
**Describe the bug**
When exporting 'Simpli List Views', file exports as a .txt and not .csv file type .

**To Reproduce**
1. Load the 'Simpli List View'
2. Select Rows
3. Click on the 'number count' of rows selected to start export
4. File downloads as a .txt and not a .csv file type

**Expected behavior**
A .csv file type should be downloaded and not a .txt file type.  

**Screenshots**
![Simpli1](https://user-images.githubusercontent.com/79225014/110664593-8a940a00-8195-11eb-8ce2-18e545320b3f.PNG)
![Simpli2](https://user-images.githubusercontent.com/79225014/110664608-8e279100-8195-11eb-8c0e-08e976ba621b.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [89.0.4389.82]

**Additional context**
I have also checked my Windows Default Programs and validated that .csv file ext's open with Excel.  I do not want to associate a .txt file type with Excel as I need a plain text editor and this would also not be a user friendly solution when adopted.

Thanks,
Sam

**Comment by sjtorre16** [comment]
**NOTE** I can rename the file from a .txt to a .csv after export and this also works, but many end users would not know how to do this and many end users also have default file ext's hidden in Win 10 OS settings.

Thanks,
Sam

**Comment by tomansley** [comment]
This issue has been resolved. As there is a workaround the next release may not be immediate. I'll let this thread know when the resolution has been released.

Cheers
Tom

**Comment by sjtorre16** [comment]
Thanks Tom!

Cheers,

Sam

**Comment by huynhwaker** [comment]
This is occurring for me.

**Comment by tomansley** [comment]
Thanks Richer. I'll look into it. Will get back to you as soon as I see what's going on.

The data is still in .csv format right?
________________________________
