### ISSUE TITLE
List View Administration Button Appearing and Disappearing without Config Change

### ISSUE THREAD

**Issue by dbsfhub** [tomansley/SimpliListViews#133]
**Describe the bug**
The 'List View Administration' icon will appear per the configuration and be useable and then after a refresh or navigating between pages it will disappear. There doesn't seem to be a way to force it back but it will eventually appear again. During this time it will also show/be missing in the Lightning Page Editor. In the Lightning Page Editor context you can sometimes get it to return by toggling the option to display it but it doesn't mean it will come back if you save or just exit back to the page you are editing. I am showing the App Page context but it occurs on all and also happens with the Example app created by the installation package. In this instance I have the component limited to 1 object with a pinned List View but that doesn't seem to affect this happening. When it does appear I am able to properly make configuration changes as you will see the screenshot shows a highlight based on a field vaue.

**Simpli List View Version**
2.146

**To Reproduce**
1. Use a component in App Page mode
2. Move to and away from the App Page and the option can disappear and reappear at will

**Expected behavior**
List View Administration should appear based on the configuration of the component.

**Screenshots**
In the example app, now you see it:
![image](https://user-images.githubusercontent.com/108283681/205339607-d63700b4-2783-4faf-afa2-1740ecd14c6d.png)

Now you don't:
![image](https://user-images.githubusercontent.com/108283681/205339651-05f98dce-1f32-456b-ba31-c02f79c52ca6.png)

On the App Page where I am using it I've had a hard time ever getting it to show but it did a couple times:
![image](https://user-images.githubusercontent.com/108283681/205339868-99b1b888-9a44-4fa4-b9b4-c6f2ca0d14e1.png)

**Desktop (please complete the following information):**
 - All Chromium

**Comment by dbsfhub** [comment]
Sorry.. forgot to attach the Log to show that it appears the config reads it should be displayed

![image](https://user-images.githubusercontent.com/108283681/205342445-37a9683b-c019-41b3-94a3-ce7f74a2b453.png)

**Comment by tomansley** [comment]
Thank you for this. I will take a look and try to resolve this issue.

**Comment by tomansley** [comment]
There are a few layers to understand for this setting.

1. Has it been configured to show or not in the GLOBAL settings? 

If NO then nobody will see the button (despite what it says on the label which is a bug!!)

IF YES then it checks the next criteria

2. Has it been configured to show or not on the PAGE settings. 

If NOT CHECKED then it should never display for any user except sys admin where it should always display

If CHECKED then it should display for all users.

NOTE that to determine whether a user is a sys admin it looks at the permission set associated to the users profile and checks that the PermissionsModifyAllData  = true.


A few questions - 

1. Are you logged in as sys admin or a regular user?
2. Does the user profile you are working with have the PermissionsModifyAllData = true or false?
3. For the list view that you are seeing changes on can you go to the list view configuration and let me know what the value is for a field - "Is Non Editable".

I am struggling to reproduce this issue.

**Comment by dbsfhub** [comment]
I had to do a refresh and haven't reinstalled as I was waiting for your next AppExchange release that included the fix you made for us on the objects not showing and other items you marked as resolved in future builds.

**Are you logged in as sys admin or a regular user?**
     I was in as an Admin and this also occurred proxied in as a non-admin user.

**Does the user profile you are working with have the PermissionsModifyAllData = true or false?**
     My Profile had it set to true, the non-admin user was false.

**For the list view that you are seeing changes on can you go to the list view configuration and let me know what the value is for a field - "Is Non Editable".**
     I checked to see if maybe I had taken a screenshot of that while it was still in my Sandbox but unfortunately no. I can tell you that this happened on every List View.

If you're having trouble reproducing it then I will just back burner the usage of this tool for now and revisit in the future and circle back if we encounter the issue again.

**Comment by tomansley** [comment]
ok, thank you. I will keep trying to reproduce and see where we go.

I am trying to push a release out by the end of the week.

**Comment by dbsfhub** [comment]
I was able to install your updated package yesterday and still see this issue although I am now having a hard time getting the button to show at all in a Spring '23 Sandbox. 

Not sure if this matters but I noticed that now I don't see the button when I edit the page that has the component on it as shown here but if I toggle it off and on then it renders in the editor.

![image](https://user-images.githubusercontent.com/108283681/214616186-181ad03b-ec4f-47c0-a61d-61fa6a7d04fe.png)
![image](https://user-images.githubusercontent.com/108283681/214616505-fc16c807-19c0-48f0-8115-7cf145223038.png)
![image](https://user-images.githubusercontent.com/108283681/214616602-fe1e4ab9-2f52-4280-9d30-af39342fc53d.png)

For the final question I couldn't answer previously 'For the list view that you are seeing changes on can you go to the list view configuration and let me know what the value is for a field - "Is Non Editable".' I am not seeing that field so guessing I am looking in the wrong place. If you can point me in the right direction I can look.

![image](https://user-images.githubusercontent.com/108283681/214617653-8c6a7331-23a3-45d5-a2ac-8984d2354740.png)
![image](https://user-images.githubusercontent.com/108283681/214617674-58abc103-ddc8-40c3-b84c-9a3336bcbb38.png)


Thanks again for all the support!
CJ

**Comment by tomansley** [comment]
Hi CJ - Unfortunately I was not able to isolate this issue so it didn't make it into the release. I will keep working on it

**Comment by suzyrokke** [comment]
Hi. I just installed this product yesterday and I'm seeing the same thing. The button was there and now it's gone. I was using the related list mode. I was only able to get it back after removing the component and recreating it on the page.

**Comment by tomansley** [comment]
Thanks for letting me know. I appreciate it. I have been investigating and
not having much luck reproducing.

I'll continue on especially since multiple people are now seeing the issue.

Cheers
Tom

**Comment by tomansley** [comment]
Hello @dbsfhub @suzyrokke,

I am asking for help. I believe I have resolved the issue but would like to get your feedback before sending the fix out to a wider audience. The latest package can be found here - https://<SFDC_URL_HERE>/packaging/installPackage.apexp?p0=04t3h000004VaM6

If you would install it and let me know if the issue is resolved or not I would greatly appreciate it. 

I'll wait on a response before marking this issue as resolved.
Thanks for the patience on this issue.

Cheers
Tom

**Comment by suzyrokke** [comment]
Cool, thanks! I'll take a look this afternoon or Monday!

**Comment by dbsfhub** [comment]
Will do some testing and report back.

**Comment by dbsfhub** [comment]
Just wanted to give a quick update that I've been doing some initial testing and so far I am seeing the button appear consistently. I'll update as I build out some additional tests.

**Comment by tomansley** [comment]
Excellent. Thank you so much for the follow-up. Will wait until I hear more
before pushing it out.

**Comment by suzyrokke** [comment]
Hi Tom,

I just did the upgrade and it appears to be working. Did some basic
clicking like I had done previously when it would just randomly disappear
and it seems to be sticking now.  I also removed it from being visible from
within the component on the related list and it went away as expected.  I
then added visibility back on the related list and the button reappeared as
expected.

Although this is not an exhaustive test, it seems to be more sticky than it
was last week!

Thanks!

**Comment by suzyrokke** [comment]
Hi Tom, I just installed this into a fresh org, and I'm guessing the update
from this thread has not made it to the app exchange download yet... as the
list view admin button is not on the list view I just added.

Let me know best next steps. Thanks,
Suzy
