### ISSUE TITLE
Allow admins to select an object so that the select object picklist does not show up for users when it isn't needed

### ISSUE THREAD

**Issue by heybethfrench** [tomansley/SimpliListViews#135]
**Is your feature request related to a problem? Please describe.**

I am looking into using your component on an Experience Site for list views related to cases.  

**Describe the solution you'd like**

Because we only want the list view to display for one Object, it would be great if the picklist to select an object did not render to reduce clicks for the end user.  Or that it would autopopulate 'Case' and display the second picklist with the related case listviews.

**Describe alternatives you've considered**

**Additional context**

**Comment by tomansley** [comment]
Great idea!

Let me look at what it would mean to get this in. I think it would be useful for many users. 

Will keep you posted.

**Comment by heybethfrench** [comment]
Awesome.  I think it might be as simple as checking to see if your comma delimited list had commas in it first, and then conditionally rendering the object picklist based on that.

**Comment by tomansley** [comment]
This functionality will be available in the next release.

**Comment by tomansley** [comment]
Released in v2.147
