### ISSUE TITLE
Creating a related list to a a record page fails.

### ISSUE THREAD

**Issue by martingaleh** [tomansley/SimpliListViews#140]
I'm probably the culprit, but I just tried to repurpose a basic existing core listview and stick it into a record page.  I want to do the same with a custom list view, but I figure baby steps...
![image](https://user-images.githubusercontent.com/283459/221671236-9632c7ef-8247-407d-adc7-346b3749d3e7.png)

barnet.xml etc.
```<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>55.0</apiVersion>
    <isExposed>true</isExposed>
    <targets>
        <target>lightning__RecordPage</target>
    </targets>
    <targetConfigs>
        <targetConfig targets="lightning__RecordPage">
            <objects>
                <object>Account</object>
            </objects>
        </targetConfig>
    </targetConfigs>
</LightningComponentBundle>```

barnett.js
```import { LightningElement, track, api   } from 'lwc';
export default class Barnett extends LightningElement {
	@api recordId;
}
```
barnett.html
```<template>
    <c-barnett
    mode="Related List View"
    has-main-title=true
    main-title="Contacts"
    single-list-view-object="Account"
    single-list-view-api-name="AllContacts"
    join-field-name="AccountId"
    join-criteria={recordId}>
</c-barnett>  
</template>```

**Comment by martingaleh** [comment]
I get it, I saw the dev example on a related list view.  It's using the simpli u i listview as the child in a parent view that contains the downclicky combo box and the listview.  I tried that.  I had a parent component named barnett.html and .js which now look like this:
```
<template>
    <c-simpli-u-i-list-views
		mode="Related List View"
		has-main-title=true
		main-title="Contact"
		single-list-view-object="Account"
		single-list-view-api-name="AllContacts"
		join-field-name="AccountId"
		join-criteria={recordId}>
</c-simpli-u-i-list-views>
</template>```
and the same js, but the only way this would work is if there's a corresponding js and html for the child component called simpliUIListViews in the common name space c.  The documentation in the example shows a sample controller: SimpliUIListViewsTestComp which would suggest the parent component would be SimpliUIListViewsTestComp.html and js.  I looked in the install with:
sfdx force:source:retrieve -m LightningComponentBundle:simpliUIListViewsTestComp

and as expected,I didn't find anything because the actual install is in a managed package, not a file in my default directory I can look to see the actual implementation.  So, if indeed the parent is supposed to contain this child c-simpliuilistviews, is there code for that?  Also, I stumbled across https://www.youtube.com/watch?v=4geKs0cqqoE&ab_channel=TomAnsley.  Does it work with custom lists too or just core lists?   Like if I type a field into the "join field" such as accountid does it just magically know to add accountid = :recordid into the predicate of the underlying soql and to get the recordid from the @api?

**Comment by tomansley** [comment]
Martin - 

I started looking into this and it looks like there are a few things going on - 

1. My example is incorrect. You need to be using the correct namespace in your LWC when using my components. So it should look something like this -     

<**simpli_lv-simpli-u-i-list-views** mode="App Page"
          page-name="App_Example_1">
    </**simpli_lv-simpli-u-i-list-views**>

3. It looks like in order to use components from other packages the org needs to have a permission change. Specifically the Lightning Web Security setting needs to be turned on. See this URL - https://help.salesforce.com/s/articleView?id=release-notes.rn_lwc_security_intro.htm&release=234&type=5

Try updating those two things and let me know how you progress.

Cheers
Tom

**Comment by martingaleh** [comment]
I was able to deploy a solution but it didn't work.  Then I tried to make a new listview specifically to test this but got:
![image](https://user-images.githubusercontent.com/283459/222935943-f680d556-8e82-417b-87d2-af70d76fd405.png)

![image](https://user-images.githubusercontent.com/283459/222935797-d8e7da53-e3f9-4f4d-bb14-51ce96dcb729.png)

**Comment by tomansley** [comment]
Make sure you add an Object Name -

[image: image.png]

**Comment by tomansley** [comment]
Martin,

From what I am seeing it looks like you are just trying to create a related list on the account object for contacts. Is this correct? If so you should be able to open the Lightning App Builder on the page and drag in a SimpliListViews component. Then set the Component Mode to "Related List View" like you did. 

For Single List View Object use "Contact"

For Single List View API Name use "ContactTest2" (from your example above) or the API name of the list view that was created.

For Joined Field Name use "ParentId". That is the field on the contact which points to the Account that has been selected.

If the above example looks accurate for what you are doing I think you might be trying to over complicate things but perhaps the example is not what you originally intended. 

Let me know if this works for you.

Cheers
Tom

**Comment by martingaleh** [comment]
Hi.
I'm just doing a related lists of contacts first as a test before I do really fancy things with the soql.
I changed the object name to Contact.  I'm not sure why I would do that if I set it to account when I created the listview.  I'm also not sure why I have to set it at all if its readily obvious from the soql

I set the join fieldname to ParentId.  Again, not sure why I'm doing that as the Contact Object does not have a ParentId field the way an attachment or account would have a parent ID field, unless we're trying to join the accountid field of the contact object to the parentid field of the account.  In this latter account, is your program smart enough to know we're on a record page for an account, the corresponding lookup field is accountid (which means I didn't add another account lookup)  and it's just a matter if determining whether I'm joining to the record page's id or parentid?

In any event, it didnt work, however unlike all the other fields the join field could have been, it returned 100 contacts from the org and not just the only contact in the org as you can see form the actual contact related list shown below it.
![image](https://user-images.githubusercontent.com/283459/223460722-4802e96d-57b1-49d4-8617-b51a75e3ee1c.png)

Finally, is there a way to make a field clickable so it goes to a page?

**Comment by martingaleh** [comment]
For related list view, I spelunked down the code and figured it out!!
![image](https://user-images.githubusercontent.com/283459/226212648-8449311b-4a17-4263-997c-8fbd3fca7062.png)

The first secret is to go on the the workbench and run select id from simpli_lv__List_View__c where simpli_lv__API_Name__c = 'your api name' and then click the id field.  If the simpli_lv__Core_ListView_Query__c
for that list view is 
select id, name from contact
The single list view object name is also the related list view object name.  It is Contact
The single list view api name is the api name you chose
The Join Field Name is the field the controller is going to use to append to the existing soql underlying the list view so that the soql become select id, name from contact where {{joinfieldname}} = recordid which is the recordid of the record page.  For the account page, it is the id of the account.

Also, I learned that there is a significant amount of debugging echoing out of the console.  This is very handy.
There is also a lot of logging in the debug logs too, but getting it is impossible.  it would have been nice just to save the logs to the listviewcontroller class, but the theoretical maneuver of setting the debug level to your user as none and the trace flag of the listviewcontroller to finest [pursuant to this](https://salesforce.stackexchange.com/questions/214380/how-are-we-supposed-to-use-debug-logs-for-a-specific-apex-class-only) didn't work for me.  In any event, this is really promising now!

**Comment by tomansley** [comment]
Martin,

You freaking rock! Nice job. I wasn't quite sure where to go with your
issue. I was about to see if you wanted to get on the phone.

I will be looking at how you did things and changing up logging a bit to
better help others.

Thank you so much for being persistent. So glad you got things working.

Cheers
Tom

**Comment by tomansley** [comment]
Martin - 

I see you asked the following question - 

_Finally, is there a way to make a field clickable so it goes to a page?_

Right now SLV is configured such that the record name is a link to the record itself and any lookup or master-detail field is a link.

Cheers
Tom

**Comment by martingaleh** [comment]
This is an unbelievable product. It’s worth the time investment. For me, it would be nice if you can see the constructed soql query string  in the console on the return because there are so many logs. It’s hard finding the one for the listviewcontroller class. Getting all the logging for that list view controller into the browser console would be even better because there is gold in there.

**Comment by tomansley** [comment]
I believe pushing more logs to the console is easily done and a great idea. I'll try get that done.
________________________________

**Comment by tomansley** [comment]
Martin,

I am going to go ahead and close this bug. Let me know if you disagree and we can reopen.

Cheers
Tom

**Comment by martingaleh** [comment]
Sorry, end of the month. I found this through my email. I want to say the product and the service for the product is far far better then salesforce, who’s service we actually have to pay for.

**Comment by tomansley** [comment]
Thanks for the kind words Martin.

I'm just a guy that loves building cool shit that people can make use of!!
:-)
