### ISSUE TITLE
Related list Listview not showing up

### ISSUE THREAD

**Issue by suzyrokke** [tomansley/SimpliListViews#145]
Hi, I just installed simplilistview into partial (newest release) and when I go to add my list view to the related list component, it doesn't populate the list view records.  I have access to the list view and can see data there. Not sure if I'm missing something or if if this is a bug. 

**Simpli List View Version**
What version of SLV is currently being used?
2.150

**To Reproduce**
I have aded the SimpliUIListviews component to the LE page
I have set the Component Mode to Related List View
I have set the Single List view API Name to my custom list view (that I have access to)
I have set the Joined Field Name to my custom object. (Asset__c)

These are
**Expected behavior**
In the dev sandbox (older release) everything worked great!

For what it's worth, I also created a mass create action just like I had in dev and it doesn't work either!  :( Not sure if these things are connected or not.

Here are some screenshots. 
I feel like it's a setting or permission or something.. but I can't remember and don't see anything amiss from Dev

![Mass Create Action Config](https://user-images.githubusercontent.com/124938086/231299970-43c3d2e0-fd8b-4692-8dd8-9c40c4c0c38a.png)
![Mass Create action error](https://user-images.githubusercontent.com/124938086/231299975-f2bedb91-e3e9-4615-9691-9f0afe1c3d78.png)
![MQC Related List](https://user-images.githubusercontent.com/124938086/231299979-4a09438f-6866-4c32-a238-871eb51548fe.png)
![MQC List view](https://user-images.githubusercontent.com/124938086/231299983-05e598a7-978b-4715-b43f-d921a8d9f6e3.png)

**Comment by suzyrokke** [comment]
Ok, thanks Tom for your response!

Hopefully it will be a quick fix or something i'm doing wrong, as I'm
hoping to get this pushed to production before April 28!

Enjoy your vacation! you deserve it!

**Comment by suzyrokke** [comment]
Hi Tom.

Sorry if my initial note was not clear.  I had installed this in a Dev
sandbox and built it out.  All worked well. then I installed the most
recent version in a Partial sandbox and the list view feature  and mass
create action aren't working.

I did remove the component and then fully reset it up again and still no
success.  (i guess i didn't remove it, save and then re-add it.  I could
try that I suppose.)

Please don't feel you need to look at this on your vacation!

**Comment by tomansley** [comment]
Suzy - did you ever get this figured out? 

Finally getting to some of the issues users have reported!!

**Comment by tomansley** [comment]
Issue not resolved but unable to reproduce as submitter no longer supporting client.
