### ISSUE TITLE
A substantial "blank" at the end of the list view

### ISSUE THREAD

**Issue by medhib-optima** [tomansley/SimpliListViews#152]
**Describe the bug**
When the Single List View component is implemented in an object page, a rather large "blank" appears at the end of the list, leaving a very large empty space and 2 list items displayed.

**Simpli List View Version**
2.167

**To Reproduce**
There's no real step involved in reproducing it: it's a component integrated into the pages of a Salesforce object.
The Component Mode is Single List View, a Custom object that fetches a CORE list.

**Expected behavior**
That there's not such a big "blank" on the list when you scroll down.

**Screenshots**
<img width="319" alt="image" src="https://github.com/tomansley/SimpliListViews/assets/138766137/13b577a9-a036-47db-ad58-4f73f55f8811">
<img width="319" alt="image" src="https://github.com/tomansley/SimpliListViews/assets/138766137/f0819090-dbac-44e5-9776-31d13ff3f54f">

<img width="1396" alt="image" src="https://github.com/tomansley/SimpliListViews/assets/138766137/1d9977f3-2199-4eb9-8050-30d79169c2a4">

**Desktop (please complete the following information):**
 - Brave (Chromium)

**Comment by tomansley** [comment]
Thanks for submitting this issue. I am aware of the problem and am actively trying to resolve. I will post a note on the issue when a fix is found and the release the fix will be associated with.

**Comment by tomansley** [comment]
Hello,

This is notification that this bug has been resolved and will be available in the next release.

Cheers
Tom
