### ISSUE TITLE
Unable to Sort Columns

### ISSUE THREAD

**Issue by reachlauraanne** [tomansley/SimpliListViews#160]
**Describe the bug**
I have created multiple list views, and am unable to sort by columns in either the Simpli list view section, or the lightning page where I have added the list component too

**Simpli List View Version**
2.307

**To Reproduce**
1. Open any list view, either through the Simplii List Examples app or through the Simplii List Views component on a lightning page
2. Click on any column and there is no ability to sort

**Expected behavior**
Click on columns to sort them ascending and descending, with options to even have secondary column sorting as shown in the help video

**Screenshots**

**Desktop (please complete the following information):**
 - Chrome

**Additional context**

**Comment by tomansley** [comment]
Hello,

I am not seeing these issues on my side so this is strange. A few things to check - 

1. Do all users have write access to the necessary simpli list view tables? See this FAQ - https://github.com/tomansley/SimpliListViews/wiki/FAQ#what-are-the-profile-security-settings-i-should-use-for-my-users-1
2. There are a few settings which dictate how sorting is done. If you have a page with an SLV component dragged on to the page then check the components config. Specifically the "Do Not Allow Sorting" checkbox should NOT be checked.
3. Another setting is on the admin page called "Do Not Allow Sorting". This should be set to No.

Let me know if any of these resolve your issue.

Cheers
Tom

**Comment by reachlauraanne** [comment]
Hi Tom,

Thankyou so much for your response, I had checked all the other areas
already, but for some reason the setting on the admin page was ticked to
not allow sorting (I was sure I had checked all the settings but must have
missed that)

Kind Regards,
Laura

[image: Reach Australia]



Laura Brown

Administrator & Executive Assistant to Scott Sanders



E: ***@***.***

M: 0412 790 033

W: www.reachaustralia.com.au

<http://www.reachaustralia.com.au/team-development-program>

**Comment by tomansley** [comment]
Closing this issue for now. Please reopen if the issue returns.
