### ISSUE TITLE
Images rendering in formula field

### ISSUE THREAD

**Issue by BDOGG32** [tomansley/SimpliListViews#20]
**Describe the bug**
When rendering images on a regular list view the image comes up however in this it comes back like this:  <img src="/resource/activityicon__UserInactive" alt="Inactive" style="height:16px; width:16px;" border="0"/>

**To Reproduce**
1. Add a formula field that will render a image
2. Add that field to the listview
3. It will give you a text string of the image (ie. <img src="/resource/activityicon__UserInactive" alt="Inactive" style="height:16px; width:16px;" border="0"/>

**Expected behavior**
Render the image similar to the regular listviews.

**Screenshots**
SimpliListView:
![image](https://user-images.githubusercontent.com/2214314/131232927-9b0598d3-31b9-495b-a3b4-ccc27df58ac8.png)

Regular Listview:
![image](https://user-images.githubusercontent.com/2214314/131232943-ab5a6403-a45a-4041-9e9c-84a1ff791ef4.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Edge
 - Version: 91.0.864.67

**Comment by tomansley** [comment]
Thanks for submitting the issue Bryan. I will look to get this resolved for the next release.

**Comment by tomansley** [comment]
Issue resolved in 2.29 released 09/24/2021
