### ISSUE TITLE
Custom List View Error

### ISSUE THREAD

**Issue by csilvestre82** [tomansley/SimpliListViews#21]
Hello,

I'm trying to build a list view for OpportunityLineItemSchedules though when I follow the steps performed on "Simpli List Views - Custom List Views" video, they seem to be slightly different than what is available on my latest download of the app in the sandbox. For example, the custom Apex Class field is not visible on the page layout and when added, it still does not show up on the page.   Furthermore, when I attempt to add the details on the SOQL query and the Table Details I'm presented with an error. Even on cloning an existing custom list view, I'm presented the same error.

`simpli_lv.ListViewTrigger: execution of AfterInsert caused by: System.DmlException: Update failed. First exception on row 0 with id a1m01000000gUObAAM; first error: CANNOT_INSERT_UPDATE_ACTIVATE_ENTITY, simpli_lv.ListViewTrigger: execution of AfterUpdate caused by: System.NullPointerException: Attempt to de-reference a null object External entry point (simpli_lv): [] (simpli_lv)
 `

**Describe the bug**
Error presented when creating a new Custom List View

**To Reproduce**
1. Go to the List View tab and click Custom 
2. Click on 'Next'
3. Add Label, Object Name, Subtype = Manual
4. Add Query and ListView Columns and click save
5. BUG: Error displayed

SOQL Query

```
         SELECT ID,
        Product_Name__c,
        Cost_Center_F__c,
        UnitPrice,
        ServiceDate,
        End_Date__c,
        Forecast_Category__c,
        Override_Revenue_Schedule__c,
                (SELECT ID,
                        ScheduleDate,
                        Revenue,
                        Description
                FROM OpportunityLineItemSchedules
                Where ScheduleDate = This_Year 
                ORDER BY OpportunityLineItemId)
FROM OpportunityLineItem
WHERE Forecast_Category__c = 'Projected'
AND HasSchedule = TRUE
```

ListView Columns:
```
[
    {
        "fieldNameOrPath":"Product_Name__c",
        "type":"string",
        "label":"Product Name"
    },
    {   
        "fieldNameOrPath":"Cost_Center_F__c",
        "type":"string",
        "label":"Cost Center"
    },
    {   
        "fieldNameOrPath":"UnitPrice",
        "type":"number",
        "label":"Sales Price"
    },
    {   
        "fieldNameOrPath":"ServiceDate",
        "type":"date",
        "label":"Start Date"
    },
    {   
        "fieldNameOrPath":"End_Date__c",
        "type":"date",
        "label":"End Date"
    },
    {   
        "fieldNameOrPath":"Forecast_Category__c",
        "type":"string",
        "label":"Forecast Category"
    },
    {   
        "fieldNameOrPath":"Override_Revenue_Schedule__c",
        "type":"boolean",
        "label":"Override Revenue Schedules?"
    },
    {   
        "fieldNameOrPath":"OpportunityLineItemSchedules.ScheduleDate",
        "type":"date",
        "label":"Schedule Date"
    },
    {   
        "fieldNameOrPath":"OpportunityLineItemSchedules.Revenue",
        "type":"number",
        "label":"Schedule Amount"
    },
    {   
        "fieldNameOrPath":"OpportunityLineItemSchedules.Description",
        "type":"string",
        "label":"Schedule Comments"
    }

]

```

**Comment by tomansley** [comment]
Hello @csilvestre82 ,

Thanks for submitting an issue! I have identified the problem and will resolve in the next release.

There is a workaround which you can use in the mean time. There is a field missing in the New page layout which is a required field. The field needs to be added to the New page layout. Unfortunately this is a managed page layout and you therefore need to create a new page layout and assign that page to yourself. Follow these steps to create and assign a new layout -

1. Go to the object manager in setup and find the List View object.
2. Select Lightning Record Pages
3. Click New button
4. Select type "Record Page".
5. Set the label and choose the "List View" object. Click next
6. Select the "Clone Salesforce Default Page" and click Finish.
7. When the Lightning App Builder is displayed select the fields component and click "Upgrade Now".
8. When the wizard start at first page click Next
9. Select "Simpli List View Layout" and click Finish.
10. Select the Information component.
11. Select the "Fields" tab in the left column to display the field components.
12. Move "Custom Apex Class" to the page.
13. Click Save.
14. Click Activate
15. Click "Assign as Org Default"
16. Click Next then click Save.

You should now be able to refresh your list view page and insert a record that is correctly added. Make sure to use "ListViewCustomManual" as the value for the custom apex class.

Cheers
Tom

**Comment by tomansley** [comment]
Haven't heard back from user. Assuming above suggestion resolved issue.

**Comment by csilvestre82** [comment]
Sorry for the delay @tomansley - Your recommendation worked.
