### ISSUE TITLE
Case Hovers in Lightning Experience

### ISSUE THREAD

**Issue by danifin** [tomansley/SimpliListViews#27]
Hi,
today on the standard list view we can hover over the case subject and see additional information regarding the case, can we get the same functionality here?
![image](https://user-images.githubusercontent.com/11889027/135967718-8d7d2024-7bf5-4fd0-aa04-d7c248f41f4f.png)

https://help.salesforce.com/s/articleView?id=sf.cases_set_up_lex_hovers.htm&type=5
https://help.salesforce.com/s/articleView?id=000325370&type=1

**Comment by tomansley** [comment]
Great idea.

Let me look into this and see what I can do.

**Comment by tomansley** [comment]
This enhancement has been completed and is available in the latest release - 2.41.

A release note will be sent out shortly.
