### ISSUE TITLE
Currency type is shown only in the U.S dollar currency

### ISSUE THREAD

**Issue by argenturatbek** [tomansley/SimpliListViews#38]
**Is your feature request related to a problem? Please describe.**

I have one currency input type [Korean Won] field (UnitPrice - 판매 단가)  on my custom object. However, when I included it in "the Simpli List View" table, it is showing me only in the U.S dollar currency type.

**Describe the solution you'd like**
I would like to be able to use different types of currency types.

**Describe alternatives you've considered**
So far, I haven't come with any alternatives.

**Additional context**
![Screen Shot 2021-11-01 at 10 11 04 AM](https://user-images.githubusercontent.com/59495051/139608514-e126a5ef-772e-4282-b9ef-79e7fab98818.png)

**Comment by tomansley** [comment]
Thanks Argen.

I will take a look and see what is happening

**Comment by tomansley** [comment]
Argen,

Currently the currency is set to only be USD. That is why that is all you see. But before I resolve this issue I want to understand a few things - 

1. Do you have a default currency set on your org?
2. Do you allow users to have different default currencies set for themselves?
3. Do you have different currencies set for different fields?
4. Do you have different currencies for different records for the same field?

I am not completely sure how currencies are allowed to be set up in Salesforce so want to try and make sure I cover all of them when I fix this issue.

Thanks
Tom

**Comment by argenturatbek** [comment]
Hi Tom, 

No problem, I am using a number input field in the list view and changing it to a currency field later in my flow process. 

    1. Yes, we do have a default currency field, which is Korean Won.
    2. Nope, we don't allow multicurrencies to be used in our org. 
    3. Nope, only Korean Won.
    4. Same. We use only Korean Won for all the records and fields.

Thank you, 
Argen

**Comment by tomansley** [comment]
Thanks Argen!

Should the currency column for you look like the following attachment?

![screenshot_2021_11_09_08_04_51](https://user-images.githubusercontent.com/375321/140938427-d77c1d80-017c-432c-91ba-bdfa29af5780.png)

**Comment by tomansley** [comment]
Argen - this will be resolved in the next release!

**Comment by tomansley** [comment]
This will be included in v2.64.

**Comment by argenturatbek** [comment]
Awesome, I really appreciate it. Thanks Tom!
