### ISSUE TITLE
Add a related list view to record lightning component to filter on current record

### ISSUE THREAD

**Issue by BECKYLEA11** [tomansley/SimpliListViews#48]
**Is your feature request related to a problem? Please describe.** I am not able to add a task list view on a project record page tab to filter for the tasks for that record
Hard to believe we cannot get a list view in salesforce to filter on the current record in a lightning component.
**Describe the solution you'd like**
I would like the project tasks to filter based on the record being viewed.
**Describe alternatives you've considered**
I have tried everything!
**Additional context**

**Comment by tomansley** [comment]
Hello,

I have recently figured out how to allow SLV to be used as a related list view. This functionality should be going into the next release.

Thanks

**Comment by BECKYLEA11** [comment]
You are incredible - thank you!!! That made my day..
Becky

**Comment by BECKYLEA11** [comment]
I just had a thought - that might not work for me as the related list is
Activity History and Past Activities, Salesforce seems to have those locked
down. Will we be able to use those related lists and order them and sort
them with SLV? A single related list will work for me if I can use task
list view but I don't know how you would be able to be imbedded in a record
page, but hopefully you do!

**Comment by tomansley** [comment]
It is true that Salesforce has the table **ActivityHistory** locked down. 

Are you referring to past Tasks?

If you are truly looking for information from the ActivityHistory table then I think we are out of luck.

**Comment by BECKYLEA11** [comment]
Task list views work the best if we can do those.

**Comment by tomansley** [comment]
This will be included in the release tomorrow - v2.64. 

I have created a video which will go out with the release notice.

**Comment by tomansley** [comment]
This will be included in the release tomorrow - v2.64.

I have created a video which will go out with the release notice.

**Comment by BECKYLEA11** [comment]
You are a rock star!
