### ISSUE TITLE
Unable to install update 

### ISSUE THREAD

**Issue by csilvestre82** [tomansley/SimpliListViews#52]
**Describe the bug**
Currently unable to install the latest package from the AppExchange (2.64) as I receive an error email alert from Salesforce in my sandbox.
In parallel, a case with Salesforce has also been created as is stated in their automated email alert.

**To Reproduce**
1. Go to AppExchange to install the app
2. Click on Install for All Users
3. Standard Salesforce install error is presented on screen and email alert is delivered titled:  **Sandbox: Package Simpli-List-Views Install Failed**

> Email body:
> 
> Your request to install package "Simpli-List-Views Spring 2021" was unsuccessful. None of the data or setup information in your salesforce.com organization was affected.
> 
> If your install continues to fail, contact Salesforce CRM Support through your normal channels and provide the following information.
> 
> Organization: 
> User: 
> Package: Simpli-List-Views (04t3h0000043tVI)
> Error Number: 109348154-456702 (-2103270111)
> Problem:
> 
> 1. (Campaign_Member_Example) In Lightning component simpli_lv:simpliUIListViews, property singleListViewApiName has an invalid value CampaignMembers.
> Campaign_Member_Example: In Lightning component simpli_lv:simpliUIListViews, property singleListViewApiName has an invalid value CampaignMembers.
> 
> 2. (List_View_Action_Record_Page1) In Lightning component simpli_lv:simpliUIListViews, property singleListViewApiName has an invalid value simpli_lv__All.
> List_View_Action_Record_Page1: In Lightning component simpli_lv:simpliUIListViews, property singleListViewApiName has an invalid value simpli_lv__All.
> 
> 3. (List_View_Config_Record_Page) In Lightning component simpli_lv:simpliUIListViews, property singleListViewApiName has an invalid value simpli_lv__All.
> List_View_Config_Record_Page: In Lightning component simpli_lv:simpliUIListViews, property singleListViewApiName has an invalid value simpli_lv__All.
> 
> 4. (PriceBook_Example) In Lightning component simpli_lv:simpliUIListViews, property singleListViewApiName has an invalid value Standard.
> PriceBook_Example: In Lightning component simpli_lv:simpliUIListViews, property singleListViewApiName has an invalid value Standard.
> 

**Expected behavior**
Update of the application after successful install

**Comment by tomansley** [comment]
Oh crap!

Thank you. I am looking at it right now!

**Comment by tomansley** [comment]
This has now been resolved. The latest package has been updated to v2.66

 https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3A00000FZ7BDUA1
