### ISSUE TITLE
Mass create new records

### ISSUE THREAD

**Issue by JeffKrakowski** [tomansley/SimpliListViews#53]
This extension https://chrome.google.com/webstore/detail/salesforce-mass-editor/mnmlmkmjjhpbfemhmhpcpfkdlgadbigf
was helpful for mass creating new records (leads, opportunities, etc. 
But it does not work in lightning.
It would be great if this feature could be added to make the list views more efficient for data entry.

**Comment by tomansley** [comment]
Thanks Jeff. Appreciate the enhancement request. Great idea. I'll look at what this means to incorporate into SLV.

**Comment by tomansley** [comment]
Released in v2.71.
