### ISSUE TITLE
Getting Errors while Deploying

### ISSUE THREAD

**Issue by argenturatbek** [tomansley/SimpliListViews#55]
**Describe the bug**
I am getting these following five errors while deploying the sandbox to the production. It says:
![image](https://user-images.githubusercontent.com/59495051/141966122-34a5d5f7-9e73-4a86-a5a8-83c68e4d000b.png)

**Additional context**
Do you know why it is happening? Is the deploying process same as usual?

**Comment by tomansley** [comment]
Hello Argen,

Are those pages that have the errors configured for Single Page List Views
or Related List Views?

There is a field on the page if you edit it through Lightning Builder
called singleListViewAPIName which needs to be filled in.

Cheers
Tom

**Comment by argenturatbek** [comment]
Thanks Tom!

**Comment by tomansley** [comment]
Argen - it looks like you reopened this issue. Are you still facing issues or is it closed?

**Comment by argenturatbek** [comment]
Good morning,  Tom!

Yes, I have tried deploying after filling the field with the API name of
the list view. But still getting the same error.

I saved the component as an App Page, not as a Single List View or a
Related List View. I could not figure it out. Is it possible if I save it
as an App Page?

Best Regards,
Argen

**Comment by argenturatbek** [comment]
Hi Tom!

Thanks to your help, we've managed to deploy the app. Appreciate it!

Best. 
Argen
