### ISSUE TITLE
Large Org Issue on Configuring Component

### ISSUE THREAD

**Issue by BDOGG32** [tomansley/SimpliListViews#63]
I am having an issue in my large org with configuring a Single List View Object.   Due to having so many objects and Listviews it can't find all of them.  When typing in Task it never pulls up the list view API Name (Show below)

![image](https://user-images.githubusercontent.com/2214314/144511024-d66864eb-c54c-4035-adc5-a929ac54862c.png)

You can see that the list views are loaded in the List Views Object here:

![image](https://user-images.githubusercontent.com/2214314/144511314-4a7c500e-caf3-4deb-bb1f-f4d5e88c8e7b.png)

The search part of the App Builder parameters is very nice but having issues with it.  Is it possible to allow for manually typing in the API Name of the Object and Listview or is there a better way to handle this?

Also the components sits forever with the processing circle/dots icon (shown below) and I can't remove the component or anything with it as I believe its trying to pull all the listviews up.  The only way to get out of this is to return back without saving.

![image](https://user-images.githubusercontent.com/2214314/144512300-bc5e33e6-984c-4948-8736-e1ed303e98f4.png)

It works fine when you allow the user to select the object and Select the listview:

![image](https://user-images.githubusercontent.com/2214314/144513127-fe16cffc-80c3-4a99-b760-42c1bd8a20fc.png)

Appreciate all the help on this and the awesome component you have created.

**Comment by tomansley** [comment]
Hi Bryan,

I appreciate you reaching out. If you have a super large org I am guessing
there is a weird scenario you have that I have not or am unable to test and
its throwing an error.

To help debug -

1. What version of the app are you using?
2. Are there any errors in the simpli_lv__List_View_Errors__c table that
point to the issue?
3. Do other list view names appear? i.e. for the Account object
4. If absolutely no list views appear in the field do you have access to
the simpli_lv__List_View__c table and the following fields -
Object_Name__c, Label__c, API_Name__c
5. How many list views do you have in the simpli_lv__List_View__c table? I
am wondering if you have so many list views and SFDC perhaps only allows a
certain number of items (typically they only allow 2000). Task would be
towards the end of list and so might be getting chopped off!

I am sure we can figure this out.

Cheers
Tom

**Comment by BDOGG32** [comment]
1. What version of the app are you using? **Newest v2.71**
2. Are there any errors in the simpli_lv__List_View_Errors__c table that
point to the issue?  **No Errors in the List View Errors Object**
3. Do other list view names appear? i.e. for the Account object - **No Account or any other comes up with none**
4. If absolutely no list views appear in the field do you have access to
the simpli_lv__List_View__c table and the following fields - **Yes I have system admin and I validated that I have access to the object and all fields**
Object_Name__c, Label__c, API_Name__c
5. How many list views do you have in the simpli_lv__List_View__c table? **Only 1573**
am wondering if you have so many list views and SFDC perhaps only allows a
certain number of items (typically they only allow 2000). Task would be
towards the end of list and so might be getting chopped off!

**Comment by tomansley** [comment]
Ok, I might have found something.

1. Go to the page you want to change the component for.
2. In a different tab, turn on debug by going to the admin app then the
admin page then find debug flag (make sure to turn off afterwards as it
creates a crap load of data).
3. edit the page. (It won't work but it would have tried)
4. Turn off debug.

Go to the List_View_Error__c tab and see if there is now logging
information. You are looking for an error log which starts out something
like "----- List View Visibility Matrix -----".

If you could send that to me. It should hopefully indicate why nothing is
being displayed.

**Comment by BDOGG32** [comment]
Yes there are 16 records with List View Visibility Matrix however only 2 are unique they are shown below:

----- ListViewHelper ----- ----- List View Visibility Matrix ----- Call Id - getListViews(MPM4_BASE__Milestone1_Project__c, PE_All_Projects_View) User - Bryan Broome (005t0000001yX8iAAE) Has Modify All - true ----- Visible List Views ----- PE All Projects View - a6or0000000Cd7GAAS ---------------------------------------

----- ListViewHelper ----- ----- List View Visibility Matrix ----- Call Id - getListViewsById({a6or0000000Cd7GAAS}, true) User - Bryan Broome (005t0000001yX8iAAE) Has Modify All - true ----- Visible List Views ----- PE All Projects View - a6or0000000Cd7GAAS ---------------------------------------

Do you need anything else?

**Comment by tomansley** [comment]
Just tested this change so that text values can be added to the component config and it looks good.

**Comment by tomansley** [comment]
Released in ver 2.72
