### ISSUE TITLE
Blank Column Issue

### ISSUE THREAD

**Issue by BDOGG32** [tomansley/SimpliListViews#64]
The Task list has resource column that is blank for all records.  It is putting the Task Name in that field.  In this case Resource is a custom object and it should just show the Resource Name not the Name of the Task that its linked to.  Shown Below:

![image](https://user-images.githubusercontent.com/2214314/144514621-e6a3254e-a6ff-41ac-8bda-355bc2ecdf94.png)

Here is the ListView Query:

`SELECT Name, MPM4_BASE__Start_Date__c, MPM4_BASE__Due_Date__c, MPM4_BASE__Complete__c, MPM4_BASE__Project_Milestone__r.Name, MPM4_BASE__Resource__r.Name, Id, RecordTypeId, CreatedDate, LastModifiedDate, SystemModstamp, MPM4_BASE__Project_Milestone__c, MPM4_BASE__Resource__c FROM MPM4_BASE__Milestone1_Task__c WHERE RecordTypeId = '012t0000000Xhal' ORDER BY Name ASC NULLS FIRST, Id ASC NULLS FIRST`

Here is how it looks in the regular list view:

![image](https://user-images.githubusercontent.com/2214314/144515045-79bc9e4b-afcd-48ae-a908-dcdf413326bb.png)

**Comment by tomansley** [comment]
I have just been able to reproduce this. Will get it resolved for next release.

**Comment by tomansley** [comment]
Released in ver 2.72
