### ISSUE TITLE
Auto Size Component

### ISSUE THREAD

**Issue by BDOGG32** [tomansley/SimpliListViews#65]
When you add the component to the lightning page its a predefined size (vertically) no matter how many records are in the listview.  When using this for multiple related lists on a detail screen it means that you have to scroll down much more because the component is taking up space even when there is very few records in the list.

Can it auto size the component based on how many records are in the listview?  If there is 1 record it sizes vertically to show enough of the component to see the 1 record and if there are 100 records then it size to the max size.  Something like this would be really nice with multiple components on top of each other.

**Comment by tomansley** [comment]
Thanks for this Bryan. I agree and will try to get the change in. Shouldn't be a big deal I believe.

**Comment by tomansley** [comment]
Released in ver 2.72
