### ISSUE TITLE
Height Dimension of Embedded List View should be dynamically resized

### ISSUE THREAD

**Issue by vchen02** [tomansley/SimpliListViews#69]
Hi I recently found the SimpliListView App and so far love all of its features. I greatly appreciate all the work you're putting on this to help all the Admins out there. 

**Describe the bug**
When I embed a Simpli List View component to a Lighting page the height seems fixed at certain pixel height (perhaps due to it being scrollable). It looks pretty bad if only a handful of records are returned or is placed on top of another Related List View. Is there anyway we can make height size dynamic based on number of records (or based on a max row count we can control) ? 

**Screenshots**
![image](https://user-images.githubusercontent.com/9257665/145447349-210fe012-c828-449e-aeec-875ada5b022b.png)

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 96.0.4664.55 (Official Build) (x86_64)

**Comment by tomansley** [comment]
Hello,

Have you installed the latest version (2.72). It was released yesterday and
should resolve this issue.

Let me know as if its not resolved I will look into it further.

Thanks
Tom

**Comment by vchen02** [comment]
Thanks it's much better w/ the latest update. 
-Victor

P.S. It's not a show stopper but the scrollable bar still bothers me. Is it possible to have a setting to disable it if one chooses ?

**Comment by tomansley** [comment]
Are you referring to the horizontal scrollbar? Can you post a screenshot of
what you are referring to?

**Comment by tomansley** [comment]
Ok, so what I am seeing is sometimes the listview data you KNOW will be only one or two records and so you want to turn scrolling off. Correct?

BTW, I use territories as well extensively and this is an awesome application for SLV. Nice job!!



________________________________

**Comment by vchen02** [comment]
Yea that's essentially it. Having a List View Config setting to turn this off would be ideal. 

By the way, does SLV support pagination in any way ? For example, setting the list to return only 10 records and the user would have to click next page to view the next 10

Yup stumbling on SLV was an early Christmas gift for me. Thanks for all the hard work!

**Comment by tomansley** [comment]
Victor - I am going to close this issue and reopen an enhancement requesting that scrollbars be turned off through config.

**Comment by tomansley** [comment]
FYI - https://github.com/tomansley/SimpliListViews/issues/70

**Comment by tomansley** [comment]
Victor - regarding pagination, its handled by SLV by paginating data automatically. There are limits that admins can set to limit or extend how many rows are brought in to the table. The whole point here is that the table (based on # fields) can be way larger than what salesforce allows without users having to click the next button (which I hate).

The idea that a user can click "give me the next page" does not exist.

Check out this video for large datasets and how it works - https://youtu.be/9eHD7ntFFs0
