### ISSUE TITLE
Ability to pass global variables like $Record.Id or $User.Id to Action Parameter

### ISSUE THREAD

**Issue by vchen02** [tomansley/SimpliListViews#73]
**Is your feature request related to a problem? Please describe.**
Hey Tom,
Thanks for the v2.80 release! I'm not sure if this is a feature request or if I am misunderstand how Action Parameters are used. Essentially, I'm trying to create a Action for a Related List I added on the Account page. The Action I'm trying to create is 'New' which takes in default values from the record Account. I tried passing in $Record.Id, recordId as the default value, but it's not rendering. Is this currently possible on SLV ?

![image](https://user-images.githubusercontent.com/9257665/146100761-bd68d98d-a96c-4796-964d-411e48fad86d.png)

**Describe the solution you'd like**

Ability to passing in common global variables like $Record.Id, $Record.Name,
$User.Id, etc

**Comment by tomansley** [comment]
Victor,

Help me understand more on what process you are trying to create.

Are you trying to get a new record action to work where the parameters you
define are defaulted when the new record page is displayed?

Or are you trying to create a custom action where parameters are passed in?

I am struggling to understand.

Cheers
Tom

**Comment by vchen02** [comment]
Hey Tom, 

Yes, this is exactly what I am trying to achieve. The challenge I'm having is not knowing how to pass the current recordId as a default parameter to the new record page.
> "Are you trying to get a new record action to work where the parameters you
> define are defaulted when the new record page is displayed?"

For extra context, this 'New' Action I'm trying to create will be on a Related List view on the Account page. When used, the AccountId should be passed to a lookup field within the new record page. 

Apologies for the confusion. Let me know if the above helps

**Comment by tomansley** [comment]
Ok, so what I am hearing is you have some object which is related to the
Account. You open an account and go to the related list. When a user clicks
the New action on the related list it should pass that Account Id into the
New page so that the new object record is automatically associated with the
account.

Correct?

**Comment by tomansley** [comment]
Victor,

Thinking about it more the ability on a RELATED LIST to automatically have the related field be set with the selected record makes a lot of sense. And looking at the code I believe this is an easy enhancement. It definitely does not happen today.

I will go ahead and get this added to the functionality.

Over and above the related Id are you hoping to default other values as well? Or was the related Id the only field for now?

Cheers
Tom

**Comment by vchen02** [comment]
Hey Tom,

That's correct. This is a very common use case for us and I presume other admins as well. 

One this sentence, you seem to indicate that one must preselect a record, click on 'New' Action and then the parameter recordId is passed to new record page ? Can we make it so it doesn't require preselection ? 
> Thinking about it more the ability on a RELATED LIST to automatically have the related field be set with the selected record makes a lot of sense.

Beyond recordId, ability to pass current logged in User Id would be awesome. A bonus would be to pass to metadata or  custom setting fields as well.

**Comment by tomansley** [comment]
It will not require preselection. I was referring to after the master
record was selected and you then go to the related lists.

Agree it should not require preselection. I will think about sending other
data as well based on your comments.

**Comment by tomansley** [comment]
Victor - this change will be in the next release. 

The enhancement will include - 

1. On a RELATED LIST to automatically have the related field on the new record be set with the master records Id. 
2. Allowing the current users id to be set on a specified field of the new record using an action parameter.

It will not include passing custom settings or metadata. This could be an enhancement in the future. I need to think more about how this would work.

Cheers
Tom

**Comment by vchen02** [comment]
Thanks Tom. Being able to relate to the master record Id and current user id is plenty enough for now.

Happy Holidays,
Victor

**Comment by tomansley** [comment]
This issue has been resolved and is now available from the appexchange in the latest package - v2.83
