### ISSUE TITLE
Inline Update to Checkbox Field Not Working (From False to True)

### ISSUE THREAD

**Issue by geekyakshay** [tomansley/SimpliListViews#74]
**Describe the bug**
We are trying to update a checkbox (Boolean) field through inline edit in the SIMPLI list view table. But component just refreshes & no updates to the checkbox are observed at a record level. 
Note: Functionality is working fine when field is already checked (true) and updated to unchecked (false). Issue is in the other way.

**Simpli List View Version**
2.72

**To Reproduce**
1. Go to SIMPLI Any List View where a checkbox field is added to the list view.
2. Double click on the checkbox field to activate the inline edit.
3. Check the unchecked checkbox for any specific record in the list view.
4. Click on the row level save button to save the record.
5. After refresh, Observe the checkbox field is not checked. No record-level update happened.

**Expected behavior**
Checkbox (Boolean) field should get checked on the record field.

**Screenshots**
Enable Inline Edit:
![image](https://user-images.githubusercontent.com/33083757/146358616-f018709c-86cf-4a7e-98f8-21b85f2736cf.png)
Check the unchecked field: 
![image](https://user-images.githubusercontent.com/33083757/146358758-5063d46c-2b8d-478e-a1aa-b9f958689d0a.png)
After Saving the Record:
![image](https://user-images.githubusercontent.com/33083757/146358936-eb4d5446-d6ff-421d-8490-3a5202274c4a.png)

No record level changes are observed.

**Desktop (please complete the following information):**
 - Browser Chrome - Version 96.0.4664.93 (Official Build) (64-bit)

**Comment by tomansley** [comment]
Thank you Akshay. I will look into this immediately.

**Comment by tomansley** [comment]
Akshay - this has been resolved and will be available in the next release.

The release should hopefully go out in a few days.

**Comment by tomansley** [comment]
This issue has been resolved and is now available from the appexchange in the latest package - v2.83
