### ISSUE TITLE
Ability to Filter List View Using Subquery

### ISSUE THREAD

**Issue by geekyakshay** [tomansley/SimpliListViews#80]
**Is your feature request related to a problem? Please describe.**
We need the ability to support the list view filter using a subquery in SOQL configured in the List View records.
Example: SELECT Name FROM ActionPlan__c WHERE Id IN (SELECT Action_Plan__c FROM APTaskTemplate__c WHERE Is_Assigned_To_Logged_In_User__c = True)

Note: Above query works fine in query builder or in apex. But throws an exception when configured in the list view record.
![image](https://user-images.githubusercontent.com/33083757/147479069-1af3f821-7126-4c34-905b-5dd254c1b71d.png)
![image](https://user-images.githubusercontent.com/33083757/147479115-0d6f65b9-d19f-4228-8ba6-a6d0be026d9f.png)

**Describe the solution you'd like**
Support for Sub-query in SOQL to filter list view records.

**Describe alternatives you've considered**
It is not possible to add or filter the records without sub-query and we seek the only feasible option as of now is to filter the records using a subquery on a child object.

**Additional context**

**Comment by tomansley** [comment]
Hi Akshay,

Yup, currently SLV doesn't support sub-queries in the WHERE clause. I will look into how much effort this will be.

Cheers
Tom

**Comment by tomansley** [comment]
Looks like we are going to be able to get this done.

It should be available in the next release, hopefully this week.

**Comment by geekyakshay** [comment]
Thanks for the quick turnaround. :)

**Comment by tomansley** [comment]
Released in version 2.100
