### ISSUE TITLE
for field of type 'Date' it shows  2020-10-19 00:00:00 instead of 2020-10-19

### ISSUE THREAD

**Issue by cristiantrif93** [tomansley/SimpliListViews#9]
**Describe the bug**
for field of type 'Date' it shows  2020-10-19 00:00:00 instead of 2020-10-19
**To Reproduce**
1. Go to List Views Example 1
2. Select an object then search for a list view that has a field of type 'Date'
3. Notice that the date is displayed in the following format: 2020-10-19 00:00:00

**Expected behavior**
Instead of displaying **2020-10-19 00:00:00** it is expected to be only the date **2020-10-19**

**Screenshots**
![date](https://user-images.githubusercontent.com/73401195/97088854-71524d00-163c-11eb-8d06-89e439280143.png)
![date1](https://user-images.githubusercontent.com/73401195/97088879-8b8c2b00-163c-11eb-81f3-30b4272ebe1e.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version: last one

**Additional context**

**Comment by sjtorre16** [comment]
Hi Cristiantrif93,

I'm having the exact same issue and I need to utilize the conditional highliting feature that we downloaded this App for based on a Date range of greater than or less than.  The filter won't work because of the time element being inserted of 00:00:00.  Did anyone ever get back with you?

**Comment by tomansley** [comment]
I just saw this defect. I did not receive notification (probably my issue). I will start looking at it and resolve for the next release.

Cheers
Tom

**Comment by tomansley** [comment]
This issue has been resolved. The update should be available soon.

![image](https://user-images.githubusercontent.com/375321/109825699-b0526980-7bff-11eb-8809-c55293704f32.png)

**Comment by tomansley** [comment]
This issue has been resolved in v1.67 which is now available here - https://partners.salesforce.com/listingSolution?listingId=a0N3A00000FZ7BDUA1
